### ISSUE TITLE
Incompatible with sbt 1.7.x

### ISSUE THREAD

**Issue by JMdoubleU** [azolotko/sbt-gitlab#43]
sbt-gitlab is currently incompatible with sbt 1.7.x due to this change: https://github.com/sbt/librarymanagement/pull/399

Error:
```
java.lang.NoClassDefFoundError: okhttp3/Interceptor
```

**Comment by azolotko** [comment]
@JMdoubleU It should be fixed in `0.1.0`. Please give it a try.

**Comment by JMdoubleU** [comment]
Thanks @azolotko! Confirmed it's fixed.
