### ISSUE TITLE
IllegalAccessError: GitlabURLHandler tried to access protected method

### ISSUE THREAD

**Issue by dpdearing** [azolotko/sbt-gitlab#47]
When `sbt-gitlab` tries to fetch a package from GitLab, I get the following error:

```
java.lang.IllegalAccessError: class org.apache.ivy.util.url.GitlabURLHandler tried to access protected 
  method 'void org.apache.ivy.util.url.URLHandler$URLInfo.<init>(boolean, long, long, java.lang.String)' 
  (org.apache.ivy.util.url.GitlabURLHandler is in unnamed module of loader 
  sbt.internal.PluginManagement$PluginClassLoader @75c9e76b; 
  org.apache.ivy.util.url.URLHandler$URLInfo is in unnamed module of 
  loader sbt.internal.MetaBuildLoader @57a3af25)
 	at org.apache.ivy.util.url.GitlabURLHandler.getURLInfo(GitlabURLHandler.java:105)
 	at org.apache.ivy.util.url.GitlabURLHandler.getURLInfo(GitlabURLHandler.java:82)
 	at org.apache.ivy.util.url.URLHandlerDispatcher.getURLInfo(URLHandlerDispatcher.java:66)
 	...
```

It's not a credentials issue, but rather it appears to be a classloader issue similar to https://github.com/sbt/sbt/issues/3498.  sbt gives each plugin a unique classloader that must have the sbt metabuild classloader as its parent, and `URLHandler$URLInfo` is not loaded in the plugin classloader.

**Comment by azolotko** [comment]
@dpdearing Thanks for the issue report! Which sbt version are you using?

**Comment by dpdearing** [comment]
> Which sbt version are you using?

@azolotko This is with sbt version 1.7.2

I am trying to migrate from `gilcloud/sbt-gitlab` for support on 1.7.x

**Comment by vaslabs** [comment]
> > Which sbt version are you using?
> 
> @azolotko This is with sbt version 1.7.2
> 
> I am trying to migrate from `gilcloud/sbt-gitlab` for support on 1.7.x

had the same issue, it's the `ThisBuild / useCoursier := false` flag that seems to trigger this issue and this version seems to be compatible with coursier

**Comment by dpdearing** [comment]
> it's the `ThisBuild / useCoursier := false` flag that seems to trigger this issue

Thank you @vaslabs!  I did have this in my build definition and removing it does appear to fix the problem.  I'll close this issue as resolved.

**Comment by dpdearing** [comment]
Sorry for the back-and-forth, but it's not clear that this actually resolved the issue after all so I'm reopening after prematurely closing.

**Comment by azolotko** [comment]
Thanks @dpdearing and @vaslabs ! I've just pushed v0.1.2 with a fix addressing this issue. It should soon appear at Maven Central. Please give it a try and let me know if there're any issues still.
