### ISSUE TITLE
Incompatibility observed between sbt 1.7.2 and >= 1.7.3

### ISSUE THREAD

**Issue by vaslabs** [azolotko/sbt-gitlab#57]
Hello,
I've observed an issue when updating the plugin to 0.1.2 and above. I've done a git bisect and isolated the issue in a particular [commit]( https://github.com/azolotko/sbt-gitlab/commit/0b36a6aa4ca63bcf968937cc1c271771bc2c785b
). The issue is related to how gitlab registry artifacts are resolved on private projects.

### Prerequisites to replicate the issue
- Have sbt use coursier (works with Ivy)
- Have a dependency from a private gitlab registry (in my case it's at least 2 repos from at least 2 different gitlab groups)

### Offending commit

Doing a git bisect I've found that the issue starts from https://github.com/azolotko/sbt-gitlab/commit/0b36a6aa4ca63bcf968937cc1c271771bc2c785b

### More details
- Also coursier API on sbt 1.7.2 seems to not be compatible with later versions of sbt
- Updating to sbt 1.7.3 or 1.8.0 does not resolve the issue
- It seems that the gitlab authentication is not added (when on coursier) properly and sbt gets 404s when trying to download the artifacts (although they exist)

I'm sceptical this is an sbt-gitlab related issue, but I'm putting this information here just in case other people face this issue. I'm still investigating what's going on with sbt >= 1.7.3 and coursier authentication

**Comment by vaslabs** [comment]
I think I've found the issue, will send a PR

**Comment by azolotko** [comment]
Thanks @vaslabs ! I've just tagged `v0.1.3` incorporating your fix. It should be synced to Maven Central in few hours or so.
